version: '3.9'

services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/monolithic_db
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
